@rootURL = http://localhost:8000
@apiEP = {{rootURL}}/api/v1
### server api
GET {{rootURL}}/shshhkjhg

### =====user api
### Get user
GET {{apiEP}}/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MTYyNTcxNjUsImV4cCI6MTcxNjI1ODA2NX0.Uc0xGRRN31ewbZ5YPikuitIpyUZ78U-D5sTsAYTAF38

### Post user
POST {{apiEP}}/users
Content-Type: application/json

{
    "fName":"Bikal",
    "emai":"email@email.com"
}